
spring:
  redis:
    #redis 配置[缓存redis]
    host: 193.168.1.4
    port: 6379
    password: password
    database: 0
    lettuce:
      pool:
        # 最大活跃链接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0

  redis2:
    #redis 配置[手动操作redis]
    host: 193.168.1.4
    port: 6379
    password: password
    database: 1


  security:
    user:
      name: admin
      password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #数据库方言
    database-platform: org.hibernate.dialect.MariaDB53Dialect
  datasource:
    db1:
      url: jdbc:mariadb://192.168.1.4:3306/auth
      username: aidai
      password: password
      driver-class-name: org.mariadb.jdbc.Driver


